### ISSUE TITLE
Is the code for evaluation only?

### ISSUE THREAD

**Issue by renjunli99** [Jbwasse2/SLING#1]
Can I use this code to reproduce the process of training  the last-mile navigation policy ?

**Comment by Jbwasse2** [comment]
For SLING as presented in the paper, we do not perform any training, all the models used are pre-trained.

We do train the "DDPPO-LMN" model from scratch. Is this the policy that you are referring to?

**Comment by renjunli99** [comment]
My apologize, I should have read the paper carefully before raise the issue.   
Regarding the last mile navigation, I suppose the only neural network used in this part is the GNN in the matching module, and that a pretrained model is implemented. Is my understanding correct? If so, can I refer to the codes in the src folder to reproduce SLING? 
I appreciate your help in clarifying this matter for me. Thank you for your time and assistance.

**Comment by Jbwasse2** [comment]
Your understanding is correct.
Here is where OVRL uses SLING:  https://github.com/Jbwasse2/SLING/blob/ovrl/habitat-lab/habitat_baselines/rl/ppo/policy.py
And here is the SLING codebase in the OVRL codebase:https://github.com/Jbwasse2/SLING/blob/ovrl/habitat-lab/habitat_baselines/rl/ppo/lastmile.py
